# Generated by Django 5.1.2 on 2024-10-22 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('solar', 'Solar'), ('wind', 'Wind'), ('grid', 'Grid'), ('generator', 'Generator')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_consumptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('energy_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('energy_efficiency', 'Energy Efficiency'), ('load_shifting', 'Load Shifting'), ('demand_response', 'Demand Response'), ('renewable_sources', 'Renewable Sources')], max_length=20)),
                ('percentage_saved', models.DecimalField(decimal_places=2, max_digits=5)),
                ('units_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
